- name: Create rclone config directory
  ansible.builtin.file:
    path: "{{ user_homedir }}/.config/rclone/"
    state: directory

- name: Copy rclone template file to remote host
  ansible.builtin.template:
    src: "rclone.conf.j2"
    dest: "{{ user_homedir }}/.config/rclone/rclone.conf"
    force: no

- name: Run rclone
  ansible.builtin.command:
    cmd: "rclone sync -P --drive-shared-with-me BYAR-maps:BYAR-maps {{ spads_install_path }}/var/spring/data/maps/"
  register: out
  changed_when: "'0 B / 0 B, -, 0 B/s' not in out.stdout"
  when: skip_rclone_sync is not true

- debug: var=out.stdout_lines
  when: skip_rclone_sync is not true