---
- name: Start SPADS
  hosts: all
#  remote_user: root

  tasks:
    - name: Enable SPADS timers
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - pr-downloader.timer
        - rclone-maps.timer
        - spads_config_updater.timer

    - name: Start SPADS secondary services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - pr-downloader.service
        - rclone-maps.service
        - spads_config_updater.service

    - name: Start and enable SPADS
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - spads.service
